"""aligned_schema_pascalcase

Revision ID: 4cca2368e0ff
Revises: 
Create Date: 2026-02-15 11:20:26.979311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cca2368e0ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_values',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Value_Group', sa.String(length=100), nullable=False),
    sa.Column('Code', sa.String(length=100), nullable=False),
    sa.Column('Label', sa.String(length=255), nullable=False),
    sa.Column('Display_Order', sa.Integer(), nullable=False),
    sa.Column('Is_Active', sa.Boolean(), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Value_Group', 'Code', name='uq_allowed_value_group_code')
    )
    with op.batch_alter_table('allowed_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowed_values_Value_Group'), ['Value_Group'], unique=False)

    op.create_table('newsletter_sections',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Newsletter_Type', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Slug', sa.String(length=100), nullable=False),
    sa.Column('Display_Order', sa.Integer(), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Requires_Image', sa.Boolean(), nullable=False),
    sa.Column('Image_Dimensions', sa.String(length=20), nullable=True),
    sa.Column('Is_Active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Newsletter_Type', 'Slug', name='uq_section_type_slug')
    )
    op.create_table('newsletters',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Newsletter_Type', sa.String(length=50), nullable=False),
    sa.Column('Publish_Date', sa.Date(), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('Created_At', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Newsletter_Type', 'Publish_Date', name='uq_newsletter_type_date')
    )
    op.create_table('schedule_configs',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Newsletter_Type', sa.String(length=50), nullable=False),
    sa.Column('Mode', sa.String(length=50), nullable=False),
    sa.Column('Submission_Deadline_Description', sa.Text(), nullable=False),
    sa.Column('Deadline_Day_Of_Week', sa.Integer(), nullable=True),
    sa.Column('Deadline_Time', sa.Time(), nullable=False),
    sa.Column('Publish_Day_Of_Week', sa.Integer(), nullable=True),
    sa.Column('Is_Daily', sa.Boolean(), nullable=False),
    sa.Column('Active_Start_Month', sa.Integer(), nullable=True),
    sa.Column('Active_End_Month', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('style_rules',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Rule_Set', sa.String(length=50), nullable=False),
    sa.Column('Category', sa.String(length=100), nullable=False),
    sa.Column('Rule_Key', sa.String(length=100), nullable=False),
    sa.Column('Rule_Text', sa.Text(), nullable=False),
    sa.Column('Is_Active', sa.Boolean(), nullable=False),
    sa.Column('Severity', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('submissions',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Category', sa.String(length=50), nullable=False),
    sa.Column('Target_Newsletter', sa.String(length=50), nullable=False),
    sa.Column('Original_Headline', sa.Text(), nullable=False),
    sa.Column('Original_Body', sa.Text(), nullable=False),
    sa.Column('Submitter_Name', sa.String(length=255), nullable=False),
    sa.Column('Submitter_Email', sa.String(length=255), nullable=False),
    sa.Column('Submitter_Notes', sa.Text(), nullable=True),
    sa.Column('Has_Image', sa.Boolean(), nullable=False),
    sa.Column('Image_Path', sa.String(length=512), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('Created_At', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('edit_versions',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Submission_Id', sa.String(length=36), nullable=False),
    sa.Column('Version_Type', sa.String(length=50), nullable=False),
    sa.Column('Headline', sa.Text(), nullable=False),
    sa.Column('Body', sa.Text(), nullable=False),
    sa.Column('Headline_Case', sa.String(length=50), nullable=True),
    sa.Column('Flags', sa.JSON(), nullable=True),
    sa.Column('Changes_Made', sa.JSON(), nullable=True),
    sa.Column('AI_Provider', sa.String(length=50), nullable=True),
    sa.Column('AI_Model', sa.String(length=100), nullable=True),
    sa.Column('Created_At', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['Submission_Id'], ['submissions.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('newsletter_items',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Newsletter_Id', sa.String(length=36), nullable=False),
    sa.Column('Submission_Id', sa.String(length=36), nullable=False),
    sa.Column('Section_Id', sa.String(length=36), nullable=False),
    sa.Column('Position', sa.Integer(), nullable=False),
    sa.Column('Final_Headline', sa.Text(), nullable=False),
    sa.Column('Final_Body', sa.Text(), nullable=False),
    sa.Column('Run_Number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Newsletter_Id'], ['newsletters.Id'], ),
    sa.ForeignKeyConstraint(['Section_Id'], ['newsletter_sections.Id'], ),
    sa.ForeignKeyConstraint(['Submission_Id'], ['submissions.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('submission_links',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Submission_Id', sa.String(length=36), nullable=False),
    sa.Column('Url', sa.Text(), nullable=False),
    sa.Column('Anchor_Text', sa.String(length=500), nullable=True),
    sa.Column('Display_Order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Submission_Id'], ['submissions.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('submission_schedule_requests',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Submission_Id', sa.String(length=36), nullable=False),
    sa.Column('Requested_Date', sa.Date(), nullable=True),
    sa.Column('Repeat_Count', sa.Integer(), nullable=False),
    sa.Column('Repeat_Note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['Submission_Id'], ['submissions.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_schedule_requests')
    op.drop_table('submission_links')
    op.drop_table('newsletter_items')
    op.drop_table('edit_versions')
    op.drop_table('submissions')
    op.drop_table('style_rules')
    op.drop_table('schedule_configs')
    op.drop_table('newsletters')
    op.drop_table('newsletter_sections')
    with op.batch_alter_table('allowed_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowed_values_Value_Group'))

    op.drop_table('allowed_values')
    # ### end Alembic commands ###
