"""initial schema

Revision ID: e9ef16c2a1f1
Revises: 
Create Date: 2026-02-13 16:43:15.359308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ef16c2a1f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('newsletter_type', sa.Enum('tdr', 'myui', name='newsletter_type_section', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_image', sa.Boolean(), nullable=False),
    sa.Column('image_dimensions', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('newsletter_type', 'slug', name='uq_section_type_slug')
    )
    op.create_table('newsletters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('newsletter_type', sa.Enum('tdr', 'myui', name='newsletter_type_nl', native_enum=False), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'ready_for_review', 'submitted', 'published', name='newsletter_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('newsletter_type', 'publish_date', name='uq_newsletter_type_date')
    )
    op.create_table('schedule_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('newsletter_type', sa.Enum('tdr', 'myui', name='newsletter_type_sched', native_enum=False), nullable=False),
    sa.Column('mode', sa.Enum('academic_year', 'summer', name='schedule_mode', native_enum=False), nullable=False),
    sa.Column('submission_deadline_description', sa.Text(), nullable=False),
    sa.Column('deadline_day_of_week', sa.Integer(), nullable=True),
    sa.Column('deadline_time', sa.Time(), nullable=False),
    sa.Column('publish_day_of_week', sa.Integer(), nullable=True),
    sa.Column('is_daily', sa.Boolean(), nullable=False),
    sa.Column('active_start_month', sa.Integer(), nullable=True),
    sa.Column('active_end_month', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_set', sa.Enum('shared', 'tdr', 'myui', name='rule_set', native_enum=False), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('rule_key', sa.String(length=100), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Enum('error', 'warning', 'info', name='rule_severity', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('faculty_staff', 'student', 'job_opportunity', 'kudos', 'in_memoriam', 'news_release', 'calendar_event', name='submission_category', native_enum=False), nullable=False),
    sa.Column('target_newsletter', sa.Enum('tdr', 'myui', 'both', name='target_newsletter', native_enum=False), nullable=False),
    sa.Column('original_headline', sa.Text(), nullable=False),
    sa.Column('original_body', sa.Text(), nullable=False),
    sa.Column('submitter_name', sa.String(length=255), nullable=False),
    sa.Column('submitter_email', sa.String(length=255), nullable=False),
    sa.Column('submitter_notes', sa.Text(), nullable=True),
    sa.Column('has_image', sa.Boolean(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('new', 'ai_edited', 'in_review', 'approved', 'scheduled', 'published', 'rejected', name='submission_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edit_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('version_type', sa.Enum('original', 'ai_suggested', 'editor_final', name='version_type', native_enum=False), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('headline_case', sa.Enum('sentence_case', 'title_case', name='headline_case', native_enum=False), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.Column('changes_made', sa.JSON(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('newsletter_id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('final_headline', sa.Text(), nullable=False),
    sa.Column('final_body', sa.Text(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['newsletter_sections.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('anchor_text', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission_schedule_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('repeat_count', sa.Integer(), nullable=False),
    sa.Column('repeat_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_schedule_requests')
    op.drop_table('submission_links')
    op.drop_table('newsletter_items')
    op.drop_table('edit_versions')
    op.drop_table('submissions')
    op.drop_table('style_rules')
    op.drop_table('schedule_configs')
    op.drop_table('newsletters')
    op.drop_table('newsletter_sections')
    # ### end Alembic commands ###
